name: Deploy to GH-pages

on:
  push:
    branches: [ "master" ]
    
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-22.04
    steps:
      - name: Git checkout public part
        uses: actions/checkout@v2

      - name: Git checkout private part
        uses: actions/checkout@v2
        with:
          repository: agronskiy/gronskiy.com-private-posts
          token: ${{ secrets.GH_TOKEN }}
          ref: main
          path: content/posts/_unlisted
      
      - name: Download Dart Sass
        run: curl -LJO https://github.com/sass/dart-sass/releases/download/1.69.5/dart-sass-1.69.5-linux-x64.tar.gz
      - name: Unpack Dart Sass
        run: |
          tar -xvf dart-sass-1.69.5-linux-x64.tar.gz
          dart-sass/sass --embedded --version          
      - name: Add Dart Sass to the PATH
        run: echo "$GITHUB_WORKSPACE/dart-sass" >> $GITHUB_PATH   
      - name: Setup hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: "0.121.1"
      
     # Generates post tags, see `./bin/tags-gen`
      - name: Generate tags 
        run: ./bin/generate-tags.sh

      - name: Generate css 
        run: ./bin/compile-sass.sh
        
      - name: Build website
        # remove --minify tag if you do not need it
        # docs: https://gohugo.io/hugo-pipes/minification/
        run: hugo --minify

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.GH_TOKEN }}
          external_repository: agronskiy/gronskiy.com-serving
          publish_dir: ./public
          publish_branch: gh-pages
          cname: gronskiy.com
          commit_message: ${{ github.event.head_commit.message }}
          force_orphan: true
