# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "master" ]
    
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-22.04
    steps:
      - name: Git checkout public part
        uses: actions/checkout@v2

      - name: Git checkout private part
        uses: actions/checkout@v2
        with:
          repository: agronskiy/website-private
          token: ${{ secrets.GH_TOKEN }}
          ref: main
          path: content/posts/_unlisted
          
      - name: Setup hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: "0.100.0"

      - name: Build website
        # remove --minify tag if you do not need it
        # docs: https://gohugo.io/hugo-pipes/minification/
        run: hugo --minify

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.GH_TOKEN }}
          external_repository: agronskiy/agronskiy.github.io
          publish_dir: ./public
          publish_branch: gh-pages
          cname: gronskiy.com
          commit_message: ${{ github.event.head_commit.message }}
